server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/Desktop/MSA_STUDY/native-file-repo

        git:
#          uri: file:///Users/lsi66/Desktop/MSA_STUDY/git-local-repo
          uri: https://github.com/MSASTUDYALONE/spring-cloud-config.git #.git 생략 가능
#          username: (private면 적어야함..)
#          password: